# This is a basic workflow that is manually triggered

name: UBC Formula Electric CI
on: [push, pull_request]

jobs:
        test_job:
                name: "Test 0"
                runs-on: ubuntu-latest
                
                steps:
                        - uses: actions/checkout@v2
                        - name: Install python packages
                          uses: actions/setup-python@v2
                          with:
                                  python-version: 3.6
                        - name: Before Install
                          run: |
                                  ./scripts/travis_ci/pull_git_submodules.sh
                                  pip install pipenv
                                  git lfs pull
                        - name: Install
                          run: |
                                  pipenv install
