# This is a basic workflow that is manually triggered

name: UBC Formula Electric CI
on: [pull_request]

jobs:
        Firmware_Tests:
                name: ${{matrix.Name}}                        
                runs-on: ubuntu-16.04
                strategy:
                        matrix:
                                include:
                                #- Name: "Build and Run x86 Tests"
                                #  env: RUN_X86_TESTS
                                #- Name: "Check Formatting"
                                #  env: RUN_FORMATTING_CHECKS
                                - Name: "Build ARM Executables"
                                  env: RUN_ARM_BUILD
                                #- Name: "Check STM32CubeMX Code Generation"
                                #  env: RUN_CUBE_CODEGEN_CHECKS 
                env: 
                        INSTALL_DIR: /usr/local
                        CUBE_INSTALL_DIR: $INSTALL_DIR/STM32CubeMX
                        PYTHONPATH: $PWD
        
                steps:                               
                        - name: Install-Addons
                          run: |               
                                  sudo apt-get update
                                  sudo apt install default-jdk
                                  sudo dpkg --add-architecture i386
                                  sudo apt-get install libncurses5
                                  sudo apt-get install libbz2-1.0
                                  sudo apt-get install libz1
                                  sudo apt-get install valgrind
                                  sudo apt-get install gcc-arm-none-eabi
                                  sudo apt-get install gdb-arm-none-eabi
                                  sudo apt-get install xvfb

                        - uses: actions/checkout@v2
                          with:
                                 fetch-depth: 50
                        - name: Install-Python-Packages
                          uses: actions/setup-python@v2
                          with:
                                  python-version: 3.6
                        - name: Before-Install
                          run: |
                                  ./scripts/travis_ci/pull_git_submodules.sh
                                  pip install pipenv
                                  git lfs pull
                                  
                        - name: Install
                          run: |
                                  pipenv install
                                  echo "${{env.INSTALL_DIR}}/bin:${{env.CUBE_INSTALL_DIR}}:$GITHUB_PATH && ./scripts/travis_ci/travis_install_binaries.sh ${{env.INSTALL_DIR}} ${{env.CUBE_INSTALL_DIR}}" >> $GITHUB_PATH
                        
                        - name: Before ${{matrix.name}}
                          run: |
                                  ./scripts/travis_ci/print_bin_versions.sh
                          env: 
                                ${{matrix.env}} : "true"
                                  
                        - name: ${{matrix.name}}
                          run: |
                                  ./scripts/travis_ci/travis_script.sh ${{env.CUBE_INSTALL_DIR}}/STM32CubeMx
                          env: 
                                ${{matrix.env}} : "true"
