# This is a basic workflow that is manually triggered

name: UBC Formula Electric CI
        
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Check-Formatting:          
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: false
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies with pipenv
        run: | 
          pip install pipenv
        env: 
                INSTALL_DIR: /usr/local
                CUBE_INSTALL_DIR: $INSTALL_DIR/STM32CubeMX
                PYTHON_PATH: $PWD
