# This is a basic workflow that is manually triggered

name: UBC Formula Electric CI
        
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  formatting_check:          
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Env Setup
        run: pip install pipenv
