# This is a basic workflow that is manually triggered

name: UBC Formula Electric CI
        
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
          
    runs-on: ubuntu-latest
    strategy:
        matrix:
                python-version: [2.7]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with: 
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
          python -m pip install --upgrade pip 
