# This is a basic workflow that is manually triggered

name: UBC Formula Electric CI
on: [push, pull_request]

jobs:
        test_job:
                name: "Firmware-Test"
                runs-on: ubuntu-latest
                env: 
                        INSTALL_DIR: /usr/local
                        CUBE_INSTALL_DIR: $INSTALL_DIR/STM32CubeMX
                        PYTHONPATH: $PWD
                
                steps:
                        - uses: actions/checkout@v2
                        - name: Install-Python-Packages
                          uses: actions/setup-python@v2
                          with:
                                  python-version: 3.6
                        - name: Before-Install
                          id: bigchungusappreciator
                          run: |
                                  ./scripts/travis_ci/pull_git_submodules.sh
                                  pip install pipenv
                                  git lfs pull
                        - name: Install
                          run: |
                                  pipenv install
                                  PATH=$INSTALL_DIR/bin:$CUBE_INSTALL_DIR:$PATH && ./scripts/travis_ci/travis_install_binaries.sh $INSTALL_DIR $CUBE_INSTALL_DIR
                                  
                        - name: Before-Script
                          run: |
                                  ./scripts/travis_ci/print_bin_versions.sh
                        - name: Script
                          run: |
                                  ./scripts/travis_ci/travis_script.sh $CUBE_INSTALL_DIR/STM32CubeMx 
